name: train-and-deploy-churn-model

on:
  push:
    branches: [ "prd" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  run-training-jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ensure scripts are runnable
        run: |
          chmod +x src/scripts/*.sh

      - name: Download cdpctl
        run: |
          src/scripts/download-cpdctl.sh

      - name: Set up cpdctl credentials
        env:
          CPD_USER_NAME: ${{ secrets.CPD_USER_NAME }}
          CPD_USER_PASSWORD: ${{ secrets.CPD_USER_PASSWORD }}
          CPD_URL: ${{ vars.CPD_URL }}
        run: |
          src/scripts/configure-cpdctl.sh

      - name: Import and code package and run job
        run: |
          src/scripts/import-code-package.sh